modLoader="javafml"
loaderVersion="${loader_version_range}"
license="All Rights Reserved"

[[mods]]
    modId="zombiecatchers"
    version="${mod_version}"
    displayName="Zombie Catchers"
    description='''
        A Minecraft mod inspired by the Zombie Catchers mobile game.
        Hunt zombies underground with a harpoon gun, craft juices, and fly with a jetpack!
    '''

[[dependencies.zombiecatchers]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.zombiecatchers]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"